TransportTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.QueryFormView.as_view(), name="index"),
]

core/models.py
from django.db import models


class City(models.Model):
    iata_code = models.CharField(max_length=3)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

core/forms.py
from django import forms


class QueryForm(forms.Form):
    query = forms.CharField(label='Please describe desired ticket', required=True,
                            widget=forms.Textarea(attrs={'rows': 15, 'cols': 75, 'style': 'resize:none;'}))

core/views.py
import requests
from django.shortcuts import render
from django.views import View

from TransportTracker.grammar.query import TicketQuery
from core.forms import QueryForm

from textx.exceptions import TextXSyntaxError, TextXSemanticError
import os
from TransportTracker.settings import BASE_DIR
from TransportTracker.execute.execute import execute_for_web
from core.models import City


class QueryFormView(View):
    form_class = QueryForm
    template_name = 'core/index.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'error_message': ''})

    def post(self, request):
        form = self.form_class(request.POST)

        query = request.POST['query'].lower()
        query = " ".join(query.splitlines())

        path = ""
        if BASE_DIR.__contains__('/'):
            path = BASE_DIR + "/TransportTracker"  # linux
        else:
            path = BASE_DIR + "\TransportTracker"  # windows

        try:
            model = execute_for_web(os.path.join(path, "grammar"), 'grammar.tx', query, True, True)
            query = TicketQuery()
            query.interpret(model)
            url = ""

            if model.transport_type.transport == 'plane':
                url = create_flight_url(model)

                if url != "":
                    flights_response = requests.get(url).json()
                    filtered_flights = []
                    if 'results' in flights_response:
                        for flight in flights_response['results']:
                            if model.ticket_class.Class in flight['travel_class'].lower():
                                filtered_flights.append(flight)

                return render(request, 'core/flight_results.html', {"from": model.From.departure_city.capitalize(),
                                                                    "to": model.to.arrival_city.capitalize(),
                                                                    "filtered_flights": filtered_flights})

            elif model.transport_type.transport == 'train':
                url = create_train_url(model)
                filtered_trains = []
                if url != "":
                    trains_response = requests.get(url).json()
                    if 'results' in trains_response:
                        for train in trains_response['results']:
                            if model.ticket_class.Class in train['itineraries']['trains']['prices']['service_class'].lower():
                                if model.price is not None:
                                    if model.price.price <= train['itineraries']['trains']['prices']['total_price'].amount and model.price.currency == train['itineraries']['trains']['prices']['total_price'].currency.lower():
                                        filtered_trains.append(train)
                                else:
                                    filtered_trains.append(train)

                return render(request, 'core/train_results.html', {"from": model.From.departure_city.capitalize(),
                                                                   "to": model.to.arrival_city.capitalize(),
                                                                   "filtered_trains": filtered_trains})
            elif model.transport_type.transport == 'bus':
                return render(request, 'core/bus_results.html')

        except TextXSyntaxError as error:
            return render(request, self.template_name, {'form': form, 'error_message': syntax_error_message(str(error))})
        except TextXSemanticError as error:
            return render(request, self.template_name, {'form': form, 'error_message': error})


def syntax_error_message(error):
    if error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|one-way|round-trip))'"):
        return "You didn't define number of tickets or ticket type (one-way or round-trip)."
    elif error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|economy|business|first|second|couchette))'"):
        return "You must define ticket class."
    elif error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|plane|bus|train))'"):
        return "You must define mean of transport (plane, train or bus)."
    elif error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|[1-9]\d*))'"):
        return "You must define number of tickets."
    elif error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|from\s))'"):
        return "You must define departure city."
    elif error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|to\s))'"):
        return "You must define arrival city."
    elif error.startswith("Expected '.*?(?=(^\s*|\s+)(\/\*|'|on\s))'"):
        return "You must define departure date."
    elif error.startswith("Expected '0[1-9]' or '[1-2][0-9]' or '3[0-1]'"):
        return "Date isn't valid. Expected date format is DD.MM.YYYY or DD/MM/YYYY."
    elif error.startswith("Expected '0[1-9]' or '1[0-2]'"):
        return "Date isn't valid. Expected date format is DD.MM.YYYY or DD/MM/YYYY."
    elif error.startswith("Expected Year"):
        return "Date isn't valid. Expected date format is DD.MM.YYYY or DD/MM/YYYY."
    elif error.startswith("Expected '/' or '.'"):
        return "Date isn't valid. Expected date format is DD.MM.YYYY or DD/MM/YYYY."


def create_flight_url(model):
    departure_city_code = ""
    arrival_city_code = ""

    if City.objects.filter(name=model.From.departure_city).exists():
        departure_city_code = City.objects.get(name=model.From.departure_city).iata_code
    if City.objects.filter(name=model.to.arrival_city).exists():
        arrival_city_code = City.objects.get(name=model.to.arrival_city).iata_code

    flights_url = ""

    if model.ticket_type.type == 'round-trip':
        if model.price is not None:
            total_price = int(model.number_of_tickets.number) * int(model.price.price)
            flights_url = 'https://api.sandbox.amadeus.com/v1.2/flights/affiliate-search?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&origin=' + departure_city_code + \
                          '&destination=' + arrival_city_code + \
                          '&departure_date=' + model.on.departure_date + \
                          '&return_date=' + model.return_date.return_date + \
                          '&adults=' + model.number_of_tickets.number + \
                          '&max_price=' + str(total_price) + \
                          '&currency=' + model.currency.currency
        else:
            flights_url = 'https://api.sandbox.amadeus.com/v1.2/flights/affiliate-search?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&origin=' + departure_city_code + \
                          '&destination=' + arrival_city_code + \
                          '&departure_date=' + model.on.departure_date + \
                          '&return_date=' + model.return_date.return_date + \
                          '&adults=' + model.number_of_tickets.number
    else:
        if model.price is not None:
            total_price = int(model.number_of_tickets.number) * int(model.price.price)
            flights_url = 'https://api.sandbox.amadeus.com/v1.2/flights/affiliate-search?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&origin=' + departure_city_code + \
                          '&destination=' + arrival_city_code + \
                          '&departure_date=' + model.on.departure_date + \
                          '&adults=' + model.number_of_tickets.number + \
                          '&max_price=' + str(total_price) + \
                          '&currency=' + model.currency.currency
        else:
            flights_url = 'https://api.sandbox.amadeus.com/v1.2/flights/affiliate-search?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&origin=' + departure_city_code + \
                          '&destination=' + arrival_city_code + \
                          '&departure_date=' + model.on.departure_date + \
                          '&adults=' + model.number_of_tickets.number
    return flights_url


def create_train_url(model):
    departure_city = model.From.departure_city
    arrival_city = model.to.arrival_city

    departure_city_url = 'https://api.sandbox.amadeus.com/v1.2/rail-stations/autocomplete?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&term=' + departure_city
    arrival_city_url = 'https://api.sandbox.amadeus.com/v1.2/rail-stations/autocomplete?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&term=' + arrival_city
    departure_city_response = requests.get(departure_city_url).json()
    arrival_city_response = requests.get(arrival_city_url).json()

    if departure_city_response and arrival_city_response:
        departure_city_code = departure_city_response[0]['value']
        arrival_city_code = arrival_city_response[0]['value']

        trains_url = 'https://api.sandbox.amadeus.com/v1.2/trains/extensive-search?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&origin=' + departure_city_code + \
                     '&destination=' + arrival_city_code + \
                     '&departure_date=' + model.on.departure_date

        if model.ticket_type.type == 'round-trip':
            return_trains_url = 'https://api.sandbox.amadeus.com/v1.2/trains/extensive-search?apikey=KKhGXAu6ANW9F3cHgBzkurG3ORgA1Bk4&origin=' + arrival_city_code + \
                                '&destination=' + departure_city_code + \
                                '&departure_date=' + model.return_date.return_date
            return_trains_response = requests.get(return_trains_url).json()
            if 'results' not in return_trains_response:
                return ""

        print(departure_city_code)
        print(arrival_city_code)
        return trains_url
    return ""

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome{% endblock %}</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'core/images/icon.png' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--Styles -->
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}">
</head>
<body>

    <nav class = "navbar navbar-inverse">
        <div class = "container-fluid">
            <!-- Header -->
            <div class = "navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                </button>
                <a class = "navbar-brand" href = "{% url 'core:index' %}">Transport Tracker</a>
            </div>
            <!-- Items -->
            <div class = "collapse navbar-collapse" id = "topNavBar">
                <ul class = "nav navbar-nav navbar-right">
                    <li>
                        <a href="#help-modal" data-toggle="modal" data-target="#help-modal"><span class="glyphicon glyphicon-book" aria-hidden = "true"><span class="link">&nbsp;Help</span></span></a>
                    </li>
                    <li>
                        <a href="#example-modal" data-toggle="modal" data-target="#example-modal"><span class="glyphicon glyphicon-th-large" aria-hidden = "true"><span class="link">&nbsp;Examples</span></span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <!-- Modal -->
    <div id="help-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header my-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" align="center">Help</h4>
            </div>
            <div class="modal-body">
                <p>Search text is not predefined.
                    User can write whatever he wants but query elements must be specified in the following order:</p>
                <ol>
                    <li>Number of tickets</li>
                    <li>Ticket type</li>
                    <li>Ticket class (only for plane and train tickets)</li>
                    <li>Transport type</li>
                    <li>Departure and arrival cities</li>
                    <li>Departure date</li>
                    <li>Return date (only for round-trip tickets)</li>
                    <li>Max price per person and currency (optional)</li>
                </ol>

                <h4>Number of tickets</h4>
                <p>Must be a positive number. It cannot be written in letters, only digits are accepted as valid number.</p>

                <h4>Ticket type</h4>
                <p>User must define whether he needs a one-way ticket or a round-trip ticket.</p>

                <h4>Ticket class</h4>
                <p>Depends on the mean of transport.
                    For plane it may be economy or business class.
                    Train classes are: first, second, couchette.</p>

                <h4>Transport type</h4>
                <p>Means of transport are plane, bus or train.</p>

                <h4>Departure and arrival cities</h4>
                <p>Order of these cities is not imposed.
                    Keyword for departure city is from and for arrival city is to. Valid city names contain only letters. If a city name contains more than one word you should separate them with - instead of whitespace.</p>

                <h4>Departure date</h4>
                <p>Key word for this date is on. Accepted date formats are: dd/mm/yyyy and dd.mm.yyyy</p>

                <h4>Return date</h4>
                <p>Key word for this date is return. Accepted date formats are: dd/mm/yyyy and dd.mm.yyyy</p>

                <h4>Max price and currency</h4>
                <p>If you wish to limit maximum ticket price you should specify your upper price limit. Keyword you must use is price. It cannot be written in letters, only digits are accepted as valid price.
                    You should also specify price currency. Avaliable currencies are EUR, RSD and USD.</p>
          </div>
        </div>
      </div>
    </div>

    <div id="example-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header my-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" align="center">Examples</h4>
            </div>
            <div class="modal-body">
                <h4>Valid plane queries</h4>
                <ul>
                    <li>I need <b>2 one-way economy</b> class <b>plane</b> tickets <b>from</b> Manchester <b>to</b> Amsterdam <b>on</b> 19/02/2018. Maximum ticket <b>price</b> is 400 <b>eur</b>.</li>
                    <li>I would like to buy <b>2 round-trip</b> tickets. Desired class is <b>economy</b>. I want to travel by  <b>plane  from</b> Belgrade <b>to</b> Milan <b>on</b> 15/03/2018 with the <b>return</b> date 20/03/2018.</li>
                </ul>
                <h4>Valid train queries</h4>
                <ul>
                    <li>We want <b>5 one-way first</b> class <b>train</b> tickets <b>from</b> Vienna <b>to</b> Prague <b>on</b> 03/06/2018. Maximum ticket <b>price</b> is 20 <b>usd</b>.</li>
                    <li>We want <b>3 round-trip second</b> class <b>train</b> tickets <b>from</b> Paris <b>to</b> Lyon <b>on</b> 01/04/2018. I want to <b>return</b> on the 06/04/2018.</li>
                </ul>
                <h4>Valid bus queries</h4>
                <ul>
                    <li>We want <b>1 one-way bus</b> ticket <b>from</b> Vienna <b>to</b> Novi<b>-</b>Sad <b>on</b> 03/06/2018. Maximum ticket <b>price</b> is 10000 <b>rsd</b>.</li>
                </ul>
          </div>
        </div>
      </div>
    </div>


    {% block body %}
    {% endblock %}

</body>
</html>

core/templates/core/bus_results.html
{% extends "core/base.html" %}

{% block title %}Bus results{% endblock %}

{% block body %}
    <h2>Bus search is not currently available</h2>
{% endblock%}

core/templates/core/flight_results.html
{% extends "core/base.html" %}
{% load flight_filters %}

{% block title %}Flight results{% endblock %}

{% block body %}
    <h2>Flights from {{ from }} to {{ to }}</h2>

    {% if filtered_flights %}
        <div class="container">
            <table class="table table-hover">
                <thead>
                    <tr class="tr-heading">
                        <th>Airline</th>
                        <th>Ticket class</th>
                        <th>Price per person</th>
                        <th>Total price</th>
                        <th>Flight type</th>
                        <th>Departure</th>
                        <th>Arrival</th>
                        <th>Duration</th>
                        <th> &nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                {% for flight in filtered_flights %}
                    <tr>
                        <td>{{ flight.airline }}</td>
                        <td>{{ flight.travel_class.lower }}</td>
                        <td>{{ flight.fare.price_per_adult.total_fare }} {{ flight.fare.currency }}</td>
                        <td>{{ flight.fare.total_price }} {{ flight.fare.currency }}</td>
                        <td>{{ flight.outbound.flights | flight_type }}</td>
                        <td>{{ flight.outbound.flights | departure }}</td>
                        <td>{{ flight.outbound.flights | arrival }}</td>
                        <td>{{ flight.outbound.duration }}</td>
                        <td><a href="{{ flight.deep_link }}"> Book </a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% else %}
        <p class="info">There are no flights that match your query. Please, try again.</p>
    {% endif %}

{% endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block body %}
 <form method="post">
    {% csrf_token %}
    {% for field in form %}
       <div class="row">
           <div class="col-md-6 col-md-offset-3">
            <label class = "text">  {{ field.label_tag }} </label>
             {{ field }}
            </div>
    {% endfor %}

        <div class="col-md-6 col-md-offset-3">
          <button type="submit" class="btn btn-search my-btn">Search</button>
            <div class = "error">
            {{ error_message }}
            </div>
        </div>
    </div>

 </form>
{% endblock %}

core/templates/core/train_results.html
{% extends "core/base.html" %}
{% load train_filters %}

{% block title %}Train results{% endblock %}

{% block body %}
    <h2>Trains from {{ from }} to {{ to }}</h2>

        {% if filtered_trains %}
            <div class="container">
                <table class="table table-hover">
                    <thead>
                        <tr class="tr-heading">
                            <th>Operating company</th>
                            <th>Train number</th>
                            <th>Ticket class</th>
                            <th>Price per person</th>
                            <th>Departure time</th>
                            <th>Departure station</th>
                            <th>Arrival time</th>
                            <th>Arrival station</th>
                            <th> &nbsp;</th>
                        </tr>
                </thead>
            <tbody>
                {% for train in filtered_trains %}
                    <tr>
                        <td>{{ train.itineraries.trains.operating_company }}</td>
                        <td>{{ train.itineraries.trains.train_number }}</td>
                        <td>{{ train.itineraries.trains.prices.service_class }}</td>
                        <td>{{ train.itineraries.trains.prices.total_price.amount }} {{ train.itineraries.trains.prices.total_price.currency }}</td>
                        <td>{{ train.itineraries.trains.departs_at | time_filter }}</td>
                        <td>{{ train.itineraries.trains.departure_station.station_name }}</td>
                        <td>{{ train.itineraries.trains.arrives_at | time_filter }}</td>
                        <td>{{ train.itineraries.trains.arrival_station.station_name }}</td>
                        <td><a href="http://www.sncf.com/"> Book </a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% else %}
        <p class="info">There are no trains that match your query. Please, try again.</p>
    {% endif %}

{% endblock%}